// apps/clientv2/src/app/components/Breadcrumb/Breadcrumb.tsx
import React from 'react';
import { NavLink } from 'react-router-dom';
import { CategoryI } from '../../interfaces';
import './Breadcrumb.scss';

interface Props {
  categories: CategoryI[];
};

export default function Breadcrumb({ categories }: Props) {
  return (
    <ul aria-label={'Listado de categorias'} role={'navigation'}>
      {categories &&
        categories.map((category: string, index: number) => (
          <li key={index}>
            <NavLink to={`/items?search=${category}`}>{category}</NavLink>
            {categories.length !== index + 1 && (
              <div aria-hidden="true" className="divider">
                {'>'}
              </div>
            )}
          </li>
        ))}
    </ul>
  );
}

// apps/client/src/app/shared/components/breadcrumb/breadcrumb.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { CategoryI } from '../../../core/interfaces';

@Component({
  selector: 'app-breadcrumb',
  templateUrl: './breadcrumb.component.html',
  styleUrls: ['./breadcrumb.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BreadcrumbComponent {
  @Input() categories: CategoryI[] = [];
}

<ul
  *ngIf="categories?.length"
  aria-label="Listado de categorias"
  role="navigation"
>
  <li *ngFor="let category of categories; last as isLast">
    <a [routerLink]="['/items']" [queryParams]="{ search: category }">{{
      category
    }}</a>
    <div aria-hidden="true" class="divider" *ngIf="!isLast">></div>
  </li>
</ul>
