// apps/client/src/app/shared/layout/header/header.component.ts
import { Component } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Store } from '@ngrx/store';
import { AppState } from '../../../core/store/app.state';
import { searchItems } from '../../../core/store/item/item.actions';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent {

  constructor(private store: Store<AppState>, 
              private router: Router) { }

  onSearch(search: string): void {
    this.router.navigate(['/items'], { queryParams: { search } });
  }

}

<header>
    <div class="container">
        <div class="logo">
            <img src="../../../../assets/images/logo_ml.png" 
                alt="Meli Logo">
        </div>
        <app-search-field (searchEvent)="onSearch($event)"></app-search-field>
    </div>
</header>

// apps/clientv2/src/app/components/Header/Header.tsx
import React from 'react'
import './Header.scss';
import logo from '../../../assets/images/logo_ml.png';
import { ReactNode } from 'react';
import { Link, useNavigate } from 'react-router-dom';

interface Props {
  children: ReactNode
};

export default function Header({children}: Props) {

  return (
    <header>
      <div className="container">
        <div className="logo">
          <Link to="">
            <img src={logo} alt="Meli Logo" />
          </Link>
        </div>
        {children}
      </div>
    </header>
  );
}
