// apps/client/src/app/shared/components/image-magnifier/image-magnifier.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ViewChild,
  ElementRef,
} from '@angular/core';
import { MagnifierEventI } from './image-magnifier.interfaces';

@Component({
  selector: 'app-image-magnifier',
  templateUrl: './image-magnifier.component.html',
  styleUrls: ['./image-magnifier.component.scss'],
})
export class ImageMagnifierComponent {
  @ViewChild('lensRef', { static: true }) lensRef!: ElementRef;

  @Input() src = '';
  @Input() width = 'auto';
  @Input() height = 'auto';
  @Input() lensWidth = 100;
  @Input() lensHeight = 100;

  @Output() eventCallBack = new EventEmitter<MagnifierEventI>();
  @Output() isHover = new EventEmitter<boolean>();

  showMagnifier = false;
  x = 0;
  y = 0;

  mouseMove(e: MouseEvent): void {
    // update cursor position
    const elem = e.target as any;
    const { top, left, width, height } = elem.getBoundingClientRect();

    // calculate cursor position on the image
    const xPosition = e.pageX - left - window.pageXOffset;
    const yPosition = e.pageY - top - window.pageYOffset;

    // calculate cursor position on the lens
    const lensElem = this.lensRef.nativeElement as any;
    let x = xPosition - lensElem.offsetWidth / 2;
    let y = yPosition - lensElem.offsetHeight / 2;
    if (x > elem.width - lensElem.offsetWidth) {
      x = elem.width - lensElem.offsetWidth;
    }
    if (x < 0) {
      x = 0;
    }
    if (y > elem.height - lensElem.offsetHeight) {
      y = elem.height - lensElem.offsetHeight;
    }
    if (y < 0) {
      y = 0;
    }

    this.x = x;
    this.y = y;

    this.eventCallBack.emit({
      width,
      height,
      x,
      y,
      lensWidth: lensElem.offsetWidth,
      lensHeight: lensElem.offsetHeight,
      src: this.src,
    });
  }

  showHideMagnifier(status: boolean): void {
    this.showMagnifier = status;
    this.isHover.emit(status);
  }
}

<div
  [style]="{ position: 'relative', height: height, width: width }"
  (mouseenter)="showHideMagnifier(true)"
  (mouseleave)="showHideMagnifier(false)"
>
  <img
    [src]="src"
    [style]="{ height: height, width: width, cursor: 'zoom-in' }"
    (mousemove)="mouseMove($event)"
    alt="img"
  />
  <div
    #lensRef
    class="lens"
    [style.display]="showMagnifier ? 'block' : 'none'"
    [style]="{
      position: 'absolute',
      pointerEvents: 'none',
      top: y + 'px',
      left: x + 'px',
      width: lensWidth + 'px',
      height: lensHeight + 'px'
    }"
  ></div>
</div>

// apps/clientv2/src/app/components/ImageMagnifier/ImageMagnifier.tsx
import { useRef, useState } from 'react';
import { MagnifierEventI } from './ImageMagnifier.interface';
import './ImageMagnifier.scss';
type EventCallBack = (item: MagnifierEventI) => void;

interface Props {
  eventCallBack: EventCallBack;
  show: (status: boolean) => void;
  src: string;
  width?: string;
  height?: string;
  lensWidth?: number;
  lensHeight?: number;
}

export default function ImageMagnifier({
  src,
  width = 'auto',
  height = 'auto',
  lensWidth = 100,
  lensHeight = 100,
  eventCallBack,
  show,
}: Props) {
  const [[x, y], setXY] = useState([0, 0]);
  const [showMagnifier, setShowMagnifier] = useState(false);
  const lensRef = useRef(null);

  function setShowStatus(status: boolean): void {
    setShowMagnifier(status);
    show(status);
  }

  return (
    <div
      style={{
        position: 'relative',
        height: height,
        width: width,
      }}
      onMouseEnter={(e) => {
        setShowStatus(true);
      }}
      onMouseLeave={() => {
        setShowStatus(false);
      }}
    >
      <img
        src={src}
        style={{ height: height, width: width, cursor: 'zoom-in' }}
        onMouseMove={(e) => {
          // update cursor position
          const elem = e.currentTarget;
          const { top, left, width, height } = elem.getBoundingClientRect();
          // calculate cursor position on the image
          const xPosition = (e.pageX - left) - window.pageXOffset;
          const yPosition = (e.pageY - top) - window.pageYOffset;

          const lensElem = lensRef.current as any;
          let x = xPosition - (lensElem.offsetWidth / 2);
          let y = yPosition - (lensElem.offsetHeight / 2);
          if (x > elem.width - lensElem.offsetWidth) {x = elem.width - lensElem.offsetWidth;}
          if (x < 0) {x = 0;}
          if (y > elem.height - lensElem.offsetHeight) {y = elem.height - lensElem.offsetHeight;}
          if (y < 0) {y = 0;}

          setXY([x, y]);
          eventCallBack({
            width,
            height,
            x,
            y,
            lensWidth: lensElem.offsetWidth,
            lensHeight: lensElem.offsetHeight,
            src: src,
          });
        }}
        alt={'img'}
      />
      <div
        className="lens"
        ref={lensRef}
        style={{
          display: `${showMagnifier ? 'block' : 'none'}`,
          position: 'absolute',
          top: `${y}px`,
          left: `${x}px`,
          width: `${lensWidth}px`,
          height: `${lensHeight}px`,
          pointerEvents: 'none',
        }}
      ></div>
    </div>
  );
}
